name: Market Pulse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 ingestion/ \
            --max-line-length=120 \
            --ignore=E251,E203,W293,W291,E303,E302,E305,E128,E266,W503,F541,E231,E122

      - name: Run tests
        run: |
          pytest tests/ -v
